apiVersion: 1
kind: instance-spec
image: trace_dns:v0.38.1
name: application-pod
paramValues:
  operator.KubeManager.namespace: demo
  operator.filter.filter: qtype==A,name==example.com.
  operator.cli.fields: k8s.podname,src,dst,name,qr,rcode,latency_ns
