apiVersion: 1
kind: instance-spec
image: trace_dns:v0.38.1
name: upstream-dns-server
paramValues:
  operator.KubeManager.all-namespaces: true
  operator.filter.filter: k8s.podName~coredns-*,qr==R,src.addr==168.63.129.16
  operator.cli.fields: k8s.podname,src,dst,name,qr,id,rcode
