apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kube-dns-visibility
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: kube-dns
  egress:
  - toEntities:
    - all
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'