apiVersion: v1
kind: Pod
metadata:
  name: dns-request-pod
  namespace: demo
spec:
  containers:
  - name: dns-request-container
    image: wbitt/network-multitool
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        echo "Requesting example.com...";
        nslookup example.com.;
        sleep 3;
        echo "Requesting unknown.example.com...";
        nslookup unknown.example.com.;
        sleep 3;
      done

